apiVersion: v1
kind: Secret
metadata:
  name: capd-eks-registrar-creds
  namespace: eksa-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "accesskey"
  AWS_SECRET_ACCESS_KEY: "secretkey"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capd-eks-registrar
  namespace: eksa-system
---
apiVersion: v1
kind: Secret
metadata:
  name: capd-eks-registrar-secret
  namespace: eksa-system
  annotations:
    kubernetes.io/service-account.name: capd-eks-registrar
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capd-eks-registrar-role
  namespace: eksa-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capd-eks-registrar-rolebinding
  namespace: eksa-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capd-eks-registrar-role
subjects:
- kind: ServiceAccount
  name: capd-eks-registrar
  namespace: eksa-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capd-eks-registrar
  namespace: eksa-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capd-eks-registrar
  template:
    metadata:
      labels:
        app: capd-eks-registrar
    spec:
      serviceAccountName: capd-eks-registrar
      containers:
      - image: ghcr.io/avp-cloud/capd-eks-registrar:main
        imagePullPolicy: Always
        name: capd-eks-registrar
        command:
        - /capd-eks-registrar
        args:
        - -namespace=eksa-system
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
              secretKeyRef:
                name: capd-eks-registrar-creds
                key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
              secretKeyRef:
                name: capd-eks-registrar-creds
                key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: "ap-south-1"
        - name: AWS_EKS_CONNECTOR_ROLE_ARN
          value: "arn:aws:iam::xxxxxxxxxxxx:role/AmazonEKSConnectorAgentRole"
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi